### ISSUE TITLE
Drive type & exterior color fields has no values in advanced search block

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-template-turbosale#8]
> I have a question regarding the advanced search on Turbosale template. 
> On demo version of Turbosale ( http://demos.subrion.org/turbosale/ ) advanced search for DRIVE TYPE and EXTERIOR COLOR (see attached file Image.png) does not work. 
Is it possible to fix this?
>
>
> ![image](https://cloud.githubusercontent.com/assets/7892851/21452812/ccfad8fc-c933-11e6-89d1-3fbf60af932a.PNG)

**Comment by oglasi** [comment]
To fix this bug on your website, edit the file 
packages/autos/includes/hook.blocks-load.php 

Find

```
$blocksData['search'] = array(
			'body_types' => $iaField->getValues('body_type', $_autosItem),
			'categories' => $iaModel->get(array('status' => iaCore::STATUS_ACTIVE, 'pid' => iaAuto::LEVEL_VENDOR)),
			'fuel_types' => $iaField->getValues('fuel_type', $_autosItem),
			'transmission' => $iaField->getValues('transmission', $_autosItem)
		);
```

And replaced with

```
$blocksData['search'] = array(
			'body_types' => $iaField->getValues('body_type', $_autosItem),
			'categories' => $iaModel->get(array('status' => iaCore::STATUS_ACTIVE, 'pid' => iaAuto::LEVEL_VENDOR)),
			'fuel_types' => $iaField->getValues('fuel_type', $_autosItem),
			'drive_type' => $iaField->getValues('drive_type', $_autosItem),
                        'exterior_color' => $iaField->getValues('exterior_color', $_autosItem),
			'transmission' => $iaField->getValues('transmission', $_autosItem)
		);
```

That's it :)

**Comment by 4unkur** [comment]
Thank you!
Issue has been already fixed in https://dev.subrion.org/issues/2459
